apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
spec:
  selector:
    matchLabels:
      app: blog-web
  replicas: 1 # Số lượng bản sao ứng dụng (Pod)
  template:
    metadata:
      labels:
        app: blog-web
    spec:
      containers:
        - name: blog-web
          image: lvhm114/blog-app
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MYSQL_HOST
              value: "mysql-service" # Tên service của MySQL trong cụm Kubernetes
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "Milvh"
            - name: MYSQL_PASS
              value: "Minh123"
            - name: MYSQL_DB
              value: "blog_web"
            - name: NODE_ENV
              value: "development"
          # env:
          #   - name: DATABASE_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-config
          #         key: DATABASE_HOST
          #   - name: DATABASE_PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-config
          #         key: DATABASE_PORT
          #   - name: DATABASE_USERNAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-config
          #         key: DATABASE_USERNAME
          #   - name: DATABASE_PASSWORD
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-config
          #         key: DATABASE_PASSWORD
          #   - name: DATABASE_NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-config
          #         key: DATABASE_NAME